#!/usr/bin/env python3
"""Git clean filter: strip speaker notes from QMD files before staging.

Reads QMD content from stdin, removes speaker notes, writes the cleaned
content to stdout. Used by git via .gitattributes.

Notes live in two places, and both have to go:

  1. A fenced div carrying the `notes` class, one per slide.
  2. A `data-notes:` block scalar under `title-slide-attributes:` in the
     YAML front matter. The title slide is generated by Quarto from the
     front matter, so a notes div cannot attach to it -- RevealJS reads
     the `data-notes` attribute off the section instead. That makes the
     front matter the only place the opening lines can live.

The div was matched with the regex `\\n::: \\{\\.notes\\}\\n.*?\\n:::\\n`,
which is one of the six spellings pandoc accepts. The other five went
straight into git (measured 2026-08-22 on a public repo whose notes are a
Korean lecture script):

    :::{.notes}            no space after the colons
    ::: notes              the bare-class form
    ::: {.notes}           with trailing whitespace
    ::::: {.notes}         more colons, as pandoc allows
    ::: {.notes} with a nested div inside -- the non-greedy match ended at
                 the inner closing fence and left the rest of the note in

So this is a scanner now, not a regex: fenced divs are tracked on a stack,
code fences are skipped, and a div whose attribute names the `notes` class
is removed whole. An unbalanced notes fence exits non-zero, which makes git
refuse the add rather than write a half-stripped file.

Setup:
    git config filter.strip-speaker-notes.clean 'python3 scripts/strip_qmd_notes.py'
    git config filter.strip-speaker-notes.smudge 'cat'
"""

import re
import sys

# A fenced-div line: three or more colons, then the attribute text (empty on
# a closing fence). Pandoc closes the innermost open div on a bare fence,
# whatever its length, so the count is not matched against the opener's.
FENCE_RE = re.compile(r'^(:{3,})\s*(.*?)\s*$')


def _names_notes(attr: str) -> bool:
    """Does this fence's attribute text put the div in the `notes` class?

    Accepts `{.notes}`, `{.notes .fragment}`, `{#id .notes}` and the bare
    `notes` form; rejects `{.callout-note}` and anything else.
    """
    if not attr:
        return False
    inner = attr[1:-1] if attr.startswith("{") and attr.endswith("}") else attr
    return any(token.lstrip(".") == "notes" for token in inner.split())


def find_note_divs(content: str) -> list:
    """[(first_line, last_line)] of every notes div, outermost only.

    Line indices are 0-based and inclusive of both fence lines. Raises
    ValueError when a notes fence is opened and never closed.
    """
    lines = content.split("\n")
    stack = []          # (is_notes, opening line index) per open div
    blocks = []
    in_fence = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = FENCE_RE.match(stripped)
        if not m:
            continue
        attr = m.group(2)
        if attr:
            stack.append((_names_notes(attr), i))
        elif stack:
            is_notes, start = stack.pop()
            # Only the outermost notes div is recorded: a notes div inside a
            # notes div is already inside the block being removed.
            if is_notes and not any(n for n, _ in stack):
                blocks.append((start, i))
    unclosed = [i for is_notes, i in stack if is_notes]
    if unclosed:
        raise ValueError(
            f"speaker-notes div opened at line {unclosed[0] + 1} is never "
            f"closed; refusing to strip a file this filter cannot read")
    return blocks


def strip_note_divs(content: str) -> str:
    """Remove every notes div, fence lines included."""
    blocks = find_note_divs(content)
    if not blocks:
        return content
    drop = set()
    for start, end in blocks:
        drop.update(range(start, end + 1))
    lines = content.split("\n")
    return "\n".join(line for i, line in enumerate(lines) if i not in drop)


def strip_title_slide_notes(content: str) -> str:
    """Remove a `data-notes:` entry from the YAML front matter.

    Handles both the block-scalar form (`data-notes: |` followed by an
    indented body) and a plain one-line value. Blank lines inside a block
    scalar belong to it, so the scan cannot stop at the first one.
    """
    lines = content.split("\n")
    out = []
    i = 0
    while i < len(lines):
        m = re.match(r'^(\s*)data-notes:', lines[i])
        if not m:
            out.append(lines[i])
            i += 1
            continue

        indent = len(m.group(1))
        i += 1
        # Consume the block-scalar body: everything blank or indented deeper.
        while i < len(lines):
            line = lines[i]
            if line.strip() and len(line) - len(line.lstrip()) <= indent:
                break
            i += 1
    return "\n".join(out)


def strip_notes(content: str) -> str:
    return strip_title_slide_notes(strip_note_divs(content))


if __name__ == "__main__":
    text = sys.stdin.read()
    try:
        sys.stdout.write(strip_notes(text))
    except ValueError as e:
        # Non-zero here makes git abort the add. Writing the input through
        # would put the notes in the index; writing nothing would empty the
        # file. Refusing is the only safe answer.
        print(f"strip_qmd_notes: {e}", file=sys.stderr)
        sys.exit(1)
