#!/usr/bin/env python3
"""Git clean filter: strip speaker notes from QMD files before staging.

Reads QMD content from stdin, removes speaker notes, writes the cleaned
content to stdout. Used by git via .gitattributes.

Notes live in two places, and both have to go:

  1. `::: {.notes} ... :::` divs, one per slide.
  2. A `data-notes:` block scalar under `title-slide-attributes:` in the
     YAML front matter. The title slide is generated by Quarto from the
     front matter, so a notes div cannot attach to it -- RevealJS reads
     the `data-notes` attribute off the section instead. That makes the
     front matter the only place the opening lines can live.

Setup:
    git config filter.strip-speaker-notes.clean 'python3 scripts/strip_qmd_notes.py'
    git config filter.strip-speaker-notes.smudge 'cat'
"""

import re
import sys


def strip_note_divs(content: str) -> str:
    """Remove ::: {.notes} ... ::: blocks from QMD content."""
    return re.sub(
        r'\n::: \{\.notes\}\n.*?\n:::\n',
        '\n',
        content,
        flags=re.DOTALL,
    )


def strip_title_slide_notes(content: str) -> str:
    """Remove a `data-notes:` entry from the YAML front matter.

    Handles both the block-scalar form (`data-notes: |` followed by an
    indented body) and a plain one-line value. Blank lines inside a block
    scalar belong to it, so the scan cannot stop at the first one.
    """
    lines = content.split("\n")
    out = []
    i = 0
    while i < len(lines):
        m = re.match(r'^(\s*)data-notes:', lines[i])
        if not m:
            out.append(lines[i])
            i += 1
            continue

        indent = len(m.group(1))
        i += 1
        # Consume the block-scalar body: everything blank or indented deeper.
        while i < len(lines):
            line = lines[i]
            if line.strip() and len(line) - len(line.lstrip()) <= indent:
                break
            i += 1
    return "\n".join(out)


def strip_notes(content: str) -> str:
    return strip_title_slide_notes(strip_note_divs(content))


if __name__ == "__main__":
    sys.stdout.write(strip_notes(sys.stdin.read()))
